const SUPABASE_URL='https://dsgnyfnddyxilakjwavu.supabase.co';
const SUPABASE_KEY='sb_publishable_4-pk8-WndWKwy_8plTVTAA_KXUNf-Lr';
const app=document.querySelector('#app'),statusEl=document.querySelector('#dbStatus'),title=document.querySelector('#title'),subtitle=document.querySelector('#subtitle');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const money=n=>(+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),date=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const feeLabel=x=>x.platform_fee_type==='percentage'?`${+x.platform_fee_value||0}%`:x.platform_fee_type==='fixed'?money(x.platform_fee_value):'Sem cobrança';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const timeout=(p,ms=9000)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error('Tempo limite na consulta.')),ms))]);
let sessionUser=null;
function fail(e){console.error(e);statusEl.textContent='● Erro';statusEl.style.color='#ef4444';app.innerHTML=`<div class="panel"><h2>Não foi possível carregar a administração</h2><p>${esc(e?.message||e)}</p><button class="primary" onclick="location.reload()">Tentar novamente</button></div>`}
async function count(t){const{count,error}=await timeout(db.from(t).select('*',{count:'exact',head:true}));if(error)throw error;return count||0}
async function rows(t,s='*',o='created_at'){let q=db.from(t).select(s);if(o)q=q.order(o,{ascending:false});const{data,error}=await timeout(q);if(error)throw error;return data||[]}
async function assertAdmin(){const r=await timeout(db.auth.getSession());sessionUser=r?.data?.session?.user;if(!sessionUser){location.href='login.html';return false}document.querySelector('#userName').textContent=sessionUser.email||'Administrador';const{data,error}=await timeout(db.from('company_members').select('role').eq('user_id',sessionUser.id).eq('role','platform_admin').limit(1).maybeSingle());if(error)throw error;if(!data){app.innerHTML='<div class="panel"><h2>Acesso negado</h2></div>';return false}statusEl.textContent='● Banco online';statusEl.style.color='#22c55e';return true}
async function overview(){const [cs,as,us,bs,ps]=await Promise.all([rows('companies'),count('auctions'),count('company_members'),count('bids'),rows('payments').catch(()=>[])]);const active=cs.filter(x=>x.active&&x.subscription_status!=='blocked'&&x.subscription_status!=='suspended').length,suspended=cs.length-active,revenue=ps.reduce((s,p)=>s+(+p.amount||0),0);app.innerHTML=`<div class="cards"><div class="card"><small>Empresas ativas</small><h2>${active}</h2><span class="up">de ${cs.length} cadastradas</span></div><div class="card"><small>Empresas suspensas</small><h2>${suspended}</h2><span class="up">Bloqueadas ou inativas</span></div><div class="card"><small>Leilões</small><h2>${as}</h2><span class="up">Total registrado</span></div><div class="card"><small>Usuários vinculados</small><h2>${us}</h2><span class="up">Membros de empresas</span></div></div><div class="panels"><div class="panel"><h3>Administração global</h3><p>Gerencie clientes, planos, vencimentos, acessos e cobrança da plataforma.</p><button class="primary" onclick="go('companies')">Gerenciar empresas</button></div><div class="panel"><h3>Financeiro</h3><div class="row"><span>Volume registrado</span><b>${money(revenue)}</b></div><div class="row"><span>Lances</span><b>${bs}</b></div><div class="row"><span>Status do banco</span><b class="badge">Conectado</b></div></div></div>`}
function companyForm(){return ''}
function bindFeeForm(){const t=document.querySelector('#feeType'),v=document.querySelector('#feeValue'),h=document.querySelector('#feeHelp');if(!t||!v)return;const sync=()=>{v.disabled=t.value==='zero';if(t.value==='zero'){v.value='0';h.textContent='Sem cobrança para este cliente.'}else if(t.value==='percentage'){v.max='100';h.textContent='Informe a porcentagem, por exemplo 5 para 5%.'}else{v.removeAttribute('max');h.textContent='Informe o preço fixo em reais.'}};t.onchange=sync;sync()}
async function companies(showForm=false){const data=await rows('companies');app.innerHTML=`${showForm?companyForm():''}<div class="panel"><div class="toolbar"><div><h3 style="margin:0">Empresas</h3><p class="muted">${data.length} empresa(s) cadastrada(s).</p></div><button class="primary" id="newCompany">+ Nova empresa</button></div><table><thead><tr><th>EMPRESA</th><th>RESPONSÁVEL</th><th>PLANO</th><th>COBRANÇA</th><th>VENCIMENTO</th><th>STATUS</th><th>AÇÕES</th></tr></thead><tbody>${data.map(x=>`<tr><td><b>${esc(x.name)}</b><br><small>${esc(x.email||x.document||'')}</small></td><td>${esc(x.responsible_name||'—')}</td><td><span class="badge">${esc(x.plan||'basico')}</span></td><td><b>${esc(feeLabel(x))}</b></td><td>${x.subscription_expires_at?new Date(x.subscription_expires_at).toLocaleDateString('pt-BR'):'—'}</td><td><span class="badge ${(!x.active||['suspended','blocked'].includes(x.subscription_status))?'warn':''}">${!x.active?'Inativa':esc(x.subscription_status||'active')}</span></td><td><button class="ghost mini toggleCompany" data-id="${x.id}" data-active="${x.active}">${x.active?'Suspender':'Ativar'}</button> <button class="ghost mini editCompany" data-id="${x.id}">Editar</button></td></tr>`).join('')||'<tr><td colspan="7">Nenhuma empresa.</td></tr>'}</tbody></table></div>`;document.querySelector('#newCompany').onclick=()=>companies(true);if(showForm){document.querySelector('#closeCompany').onclick=()=>companies();document.querySelector('#companyForm').onsubmit=createCompany;bindFeeForm()}document.querySelectorAll('.toggleCompany').forEach(b=>b.onclick=()=>toggleCompany(b.dataset.id,b.dataset.active==='true'));document.querySelectorAll('.editCompany').forEach(b=>b.onclick=()=>editCompany(b.dataset.id,data));}
async function createCompany(){}
async function toggleCompany(id,isActive){if(!confirm(isActive?'Suspender esta empresa?':'Ativar esta empresa?'))return;const{error}=await db.from('companies').update({active:!isActive,subscription_status:isActive?'suspended':'active',updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert('Erro: '+error.message);companies()}
async function editCompany(){}
async function auctions(){const d=await rows('auctions');app.innerHTML=`<div class="panel"><h3>Leilões da plataforma</h3><table><thead><tr><th>TÍTULO</th><th>STATUS</th><th>EMPRESA</th><th>INÍCIO</th><th>FIM</th></tr></thead><tbody>${d.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td><span class="badge">${esc(x.status)}</span></td><td>${esc(x.company_id)}</td><td>${date(x.starts_at)}</td><td>${date(x.ends_at)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum leilão.</td></tr>'}</tbody></table></div>`}
async function users(){
  const [members,companiesData]=await Promise.all([
    rows('company_members','company_id,user_id,role,created_at'),
    rows('companies','id,name,responsible_name,email',null)
  ]);
  const companyMap=new Map(companiesData.map(c=>[c.id,c]));
  app.innerHTML=`<div class="panel"><h3>Usuários e acessos</h3><table><thead><tr><th>CLIENTE</th><th>EMPRESA</th><th>E-MAIL</th><th>PERFIL</th><th>CRIADO EM</th></tr></thead><tbody>${members.map(x=>{
    const company=companyMap.get(x.company_id)||{};
    const isAdmin=x.role==='platform_admin';
    const clientName=isAdmin?(sessionUser?.user_metadata?.responsible_name||sessionUser?.user_metadata?.name||'Administrador'):(company.responsible_name||company.name||'Cliente');
    const companyName=isAdmin?'JP Leilões':(company.name||'—');
    const email=isAdmin?(sessionUser?.email||company.email||'—'):(company.email||'—');
    return `<tr><td><b>${esc(clientName)}</b></td><td>${esc(companyName)}</td><td>${esc(email)}</td><td><span class="badge">${esc(x.role)}</span></td><td>${date(x.created_at)}</td></tr>`;
  }).join('')||'<tr><td colspan="5">Nenhum usuário cadastrado.</td></tr>'}</tbody></table></div>`
}
async function finance(){const d=await rows('payments').catch(()=>[]),total=d.reduce((s,p)=>s+(+p.amount||0),0);app.innerHTML=`<div class="cards"><div class="card"><small>Pagamentos</small><h2>${d.length}</h2></div><div class="card"><small>Volume</small><h2>${money(total)}</h2></div></div><div class="panel"><h3>Movimentações financeiras</h3>${d.length?`<table><thead><tr><th>ID</th><th>VALOR</th><th>STATUS</th><th>DATA</th></tr></thead><tbody>${d.map(x=>`<tr><td>${esc(x.id)}</td><td><b>${money(x.amount)}</b></td><td><span class="badge">${esc(x.status)}</span></td><td>${date(x.created_at)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Nenhum pagamento registrado.</p>'}</div>`}
async function system(){const ts=['companies','company_members','auctions','lots','bids','participants','payments'],stats=await Promise.all(ts.map(async t=>[t,await count(t).catch(()=>null)]));app.innerHTML=`<div class="panel"><h3>Sistema</h3><div class="row"><span>Supabase</span><b class="badge">Online</b></div><div class="row"><span>Administrador</span><b>${esc(sessionUser?.email)}</b></div></div><div class="panel"><h3>Banco de dados</h3>${stats.map(([t,n])=>`<div class="row"><span>${t}</span><b>${n===null?'Sem acesso':n+' registro(s)'}</b></div>`).join('')}</div>`}
const pages={overview:[overview,'Visão geral','Administração global da plataforma'],companies:[companies,'Empresas','Clientes, planos, assinaturas e cobrança'],auctions:[auctions,'Leilões','Visão global dos leilões'],users:[users,'Usuários','Acessos e perfis da plataforma'],finance:[finance,'Financeiro','Movimentação financeira global'],system:[system,'Sistema','Saúde da plataforma']};
async function go(n){const sidebar=document.querySelector('.sidebar');if(sidebar)sidebar.classList.remove('open');const p=pages[n]||pages.overview;title.textContent=p[1];subtitle.textContent=p[2];document.querySelectorAll('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===n));app.innerHTML='<div class="panel"><p>Carregando...</p></div>';try{await p[0]()}catch(e){fail(e)}}
document.querySelectorAll('#adminNav button').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelector('#logoutButton').onclick=async()=>{await db.auth.signOut();location.href='login.html'};document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
(async()=>{try{if(await assertAdmin())await go('overview')}catch(e){fail(e)}})();