// Extensão do painel do dono: criação e edição completa de empresas.
const ownerCompanyForm=companyForm;
companyForm=function(x=null){
  const editing=!!x,sel=(a,b)=>a===b?' selected':'',feeType=x?.platform_fee_type||'zero',feeValue=Number(x?.platform_fee_value||0),expires=x?.subscription_expires_at?String(x.subscription_expires_at).slice(0,10):'';
  return `<div class="panel"><div class="toolbar"><div><h3 style="margin:0">${editing?'Editar empresa':'Nova empresa cliente'}</h3><p class="muted">${editing?'Altere os dados, plano, status, vencimento e cobrança do cliente.':'Cadastre a empresa, defina a cobrança e crie automaticamente o acesso do proprietário.'}</p></div><button class="ghost" id="closeCompany">Fechar</button></div><form id="companyForm" class="grid2"><label>Nome da empresa<input name="name" required value="${esc(x?.name||'')}"></label><label>CNPJ / CPF<input name="document" value="${esc(x?.document||'')}"></label><label>Responsável<input name="responsible_name" required value="${esc(x?.responsible_name||'')}"></label><label>E-mail de acesso<input name="email" type="email" required autocomplete="email" value="${esc(x?.email||'')}"></label>${editing?'':`<label>Senha inicial<input name="password" type="password" minlength="6" required autocomplete="new-password"><small>Mínimo de 6 caracteres. O cliente poderá usar esta senha no primeiro acesso.</small></label>`}<label>Telefone<input name="phone" value="${esc(x?.phone||'')}"></label><label>Plano<select name="plan"><option value="teste"${sel(x?.plan,'teste')}>Teste</option><option value="basico"${sel(x?.plan||'basico','basico')}>Básico</option><option value="profissional"${sel(x?.plan,'profissional')}>Profissional</option><option value="premium"${sel(x?.plan,'premium')}>Premium</option></select></label><label>Status<select name="subscription_status"><option value="trial"${sel(x?.subscription_status,'trial')}>Teste</option><option value="active"${sel(x?.subscription_status||'active','active')}>Ativa</option><option value="suspended"${sel(x?.subscription_status,'suspended')}>Suspensa</option><option value="blocked"${sel(x?.subscription_status,'blocked')}>Bloqueada</option></select></label><label>Vencimento<input name="subscription_expires_at" type="date" value="${esc(expires)}"></label><label>Forma de cobrança<select name="platform_fee_type" id="feeType"><option value="zero"${sel(feeType,'zero')}>Sem cobrança / valor zerado</option><option value="percentage"${sel(feeType,'percentage')}>Porcentagem (%)</option><option value="fixed"${sel(feeType,'fixed')}>Preço fixo (R$)</option></select></label><label>Valor da cobrança<input name="platform_fee_value" id="feeValue" type="number" min="0" step="0.01" value="${feeValue}"><small id="feeHelp"></small></label><div><button class="primary" type="submit">${editing?'Salvar alterações':'Criar empresa e acesso'}</button></div></form></div>`;
};

createCompany=async function(e){
  e.preventDefault();const form=e.currentTarget,button=form.querySelector('button[type="submit"]'),f=new FormData(form),feeType=String(f.get('platform_fee_type')||'zero'),feeValue=feeType==='zero'?0:Number(f.get('platform_fee_value')||0);
  if(!['zero','percentage','fixed'].includes(feeType))return alert('Forma de cobrança inválida.');if(!Number.isFinite(feeValue)||feeValue<0||(feeType==='percentage'&&feeValue>100))return alert('Valor de cobrança inválido.');
  const payload={name:String(f.get('name')||'').trim(),document:String(f.get('document')||'').trim()||null,responsible_name:String(f.get('responsible_name')||'').trim()||null,email:String(f.get('email')||'').trim().toLowerCase(),password:String(f.get('password')||''),phone:String(f.get('phone')||'').trim()||null,plan:f.get('plan'),subscription_status:f.get('subscription_status'),subscription_expires_at:f.get('subscription_expires_at')||null,platform_fee_type:feeType,platform_fee_value:feeValue};
  if(!payload.name||!payload.email||payload.password.length<6)return alert('Informe empresa, e-mail e uma senha com pelo menos 6 caracteres.');button.disabled=true;button.textContent='Criando empresa e acesso...';
  try{const {data,error}=await db.functions.invoke('admin-create-company',{body:payload});if(error)throw error;if(data?.error)throw new Error(data.error);alert(`Empresa criada com sucesso!\n\nLogin do cliente: ${payload.email}\nPerfil: owner`);await companies()}catch(err){let message=err?.message||String(err);try{if(err?.context){const body=await err.context.json();message=body?.error||message}}catch(_){}alert('Não foi possível criar a empresa e o acesso: '+message);button.disabled=false;button.textContent='Criar empresa e acesso'}
};

editCompany=async function(id,data){
  const x=data.find(v=>String(v.id)===String(id));if(!x)return alert('Empresa não encontrada.');
  app.innerHTML=companyForm(x);document.querySelector('#closeCompany').onclick=()=>companies();bindFeeForm();
  document.querySelector('#companyForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button[type="submit"]'),f=new FormData(form),type=String(f.get('platform_fee_type')||'zero'),value=type==='zero'?0:Number(f.get('platform_fee_value')||0);if(!Number.isFinite(value)||value<0||(type==='percentage'&&value>100))return alert('Valor de cobrança inválido.');const status=String(f.get('subscription_status')||'active'),payload={name:String(f.get('name')||'').trim(),document:String(f.get('document')||'').trim()||null,responsible_name:String(f.get('responsible_name')||'').trim()||null,email:String(f.get('email')||'').trim().toLowerCase()||null,phone:String(f.get('phone')||'').trim()||null,plan:f.get('plan'),subscription_status:status,subscription_expires_at:f.get('subscription_expires_at')||null,platform_fee_type:type,platform_fee_value:value,active:!['suspended','blocked'].includes(status),updated_at:new Date().toISOString()};if(!payload.name)return alert('Informe o nome da empresa.');button.disabled=true;button.textContent='Salvando...';const{error}=await db.from('companies').update(payload).eq('id',id);if(error){button.disabled=false;button.textContent='Salvar alterações';return alert('Erro: '+error.message)}alert('Empresa atualizada com sucesso.');companies()};
};