const SUPABASE_URL='https://dsgnyfnddyxilakjwavu.supabase.co';
const SUPABASE_KEY='sb_publishable_4-pk8-WndWKwy_8plTVTAA_KXUNf-Lr';
const app=document.querySelector('#app'),statusEl=document.querySelector('#dbStatus'),title=document.querySelector('#title'),subtitle=document.querySelector('#subtitle');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>(+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
if(!window.supabase){app.innerHTML='<div class="panel"><h2>Supabase indisponível</h2><p>Recarregue a página.</p></div>';throw new Error('Supabase SDK indisponível')}
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const timeout=(p,ms=9000)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error('Tempo limite na consulta.')),ms))]);
let sessionUser=null;
function fail(e){console.error(e);statusEl.textContent='● Erro';statusEl.style.color='#ef4444';app.innerHTML=`<div class="panel"><h2>Não foi possível carregar a administração</h2><p>${esc(e?.message||e)}</p><button class="primary" onclick="location.reload()">Tentar novamente</button></div>`}
async function count(table){const{count,error}=await timeout(db.from(table).select('*',{count:'exact',head:true}));if(error)throw error;return count||0}
async function rows(table,select='*',order='created_at'){let q=db.from(table).select(select);if(order)q=q.order(order,{ascending:false});const{data,error}=await timeout(q);if(error)throw error;return data||[]}
async function assertAdmin(){const r=await timeout(db.auth.getSession());sessionUser=r?.data?.session?.user;if(!sessionUser){location.href='login.html';return false}document.querySelector('#userName').textContent=sessionUser.email||'Administrador';const{data,error}=await timeout(db.from('company_members').select('role').eq('user_id',sessionUser.id).eq('role','platform_admin').limit(1).maybeSingle());if(error)throw error;if(!data){app.innerHTML='<div class="panel"><h2>Acesso negado</h2><p>Este usuário não possui o perfil platform_admin.</p></div>';return false}statusEl.textContent='● Banco online';statusEl.style.color='#22c55e';return true}
async function overview(){const [companies,auctions,users,bids,payments]=await Promise.all([count('companies'),count('auctions'),count('company_members'),count('bids'),rows('payments').catch(()=>[])]);const revenue=payments.reduce((s,p)=>s+(+p.amount||+p.value||0),0);app.innerHTML=`<div class="cards"><div class="card"><small>Empresas</small><h2>${companies}</h2><span class="up">Cadastradas na plataforma</span></div><div class="card"><small>Leilões</small><h2>${auctions}</h2><span class="up">Total registrado</span></div><div class="card"><small>Usuários vinculados</small><h2>${users}</h2><span class="up">Membros de empresas</span></div><div class="card"><small>Lances</small><h2>${bids}</h2><span class="up">Total da plataforma</span></div></div><div class="panels"><div class="panel"><h3>Administração global</h3><p>Você está no painel exclusivo do dono do sistema.</p><p class="muted">Gerencie empresas, acompanhe leilões, usuários e a operação financeira em um único lugar.</p></div><div class="panel"><h3>Financeiro</h3><div class="row"><span>Volume registrado</span><b>${money(revenue)}</b></div><div class="row"><span>Status do banco</span><b class="badge">Conectado</b></div></div></div>`}
async function companies(){const data=await rows('companies');app.innerHTML=`<div class="panel"><h3>Empresas</h3><p class="muted">${data.length} empresa(s) cadastrada(s).</p><table><thead><tr><th>EMPRESA</th><th>SLUG</th><th>E-MAIL</th><th>TELEFONE</th><th>STATUS</th><th>CRIADA EM</th></tr></thead><tbody>${data.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.slug)}</td><td>${esc(x.email||'—')}</td><td>${esc(x.phone||'—')}</td><td><span class="badge">${x.active===false?'Inativa':'Ativa'}</span></td><td>${date(x.created_at)}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma empresa cadastrada.</td></tr>'}</tbody></table></div>`}
async function auctions(){const data=await rows('auctions');app.innerHTML=`<div class="panel"><h3>Leilões da plataforma</h3><table><thead><tr><th>TÍTULO</th><th>STATUS</th><th>EMPRESA</th><th>INÍCIO</th><th>FIM</th></tr></thead><tbody>${data.map(x=>`<tr><td><b>${esc(x.title||x.name||'Leilão')}</b></td><td><span class="badge">${esc(x.status||'—')}</span></td><td>${esc(x.company_id||'—')}</td><td>${date(x.starts_at)}</td><td>${date(x.ends_at)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum leilão cadastrado.</td></tr>'}</tbody></table></div>`}
async function users(){const data=await rows('company_members','company_id,user_id,role,created_at');app.innerHTML=`<div class="panel"><h3>Usuários e acessos</h3><p class="muted">Esta visão mostra os vínculos de usuários com empresas. E-mails do Auth não são expostos diretamente pelo navegador.</p><table><thead><tr><th>USER ID</th><th>EMPRESA</th><th>PERFIL</th><th>CRIADO EM</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(x.user_id)}</td><td>${esc(x.company_id)}</td><td><span class="badge">${esc(x.role)}</span></td><td>${date(x.created_at)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum vínculo encontrado.</td></tr>'}</tbody></table></div>`}
async function finance(){const data=await rows('payments').catch(()=>[]);const total=data.reduce((s,p)=>s+(+p.amount||+p.value||0),0);app.innerHTML=`<div class="cards"><div class="card"><small>Pagamentos</small><h2>${data.length}</h2></div><div class="card"><small>Volume</small><h2>${money(total)}</h2></div></div><div class="panel"><h3>Movimentações financeiras</h3>${data.length?`<table><thead><tr><th>ID</th><th>VALOR</th><th>STATUS</th><th>DATA</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(x.id)}</td><td><b>${money(x.amount??x.value)}</b></td><td><span class="badge">${esc(x.status||'—')}</span></td><td>${date(x.created_at)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Nenhum pagamento registrado.</p>'}</div>`}
async function system(){const tables=['companies','company_members','auctions','lots','bids','participants','payments'];const stats=await Promise.all(tables.map(async t=>[t,await count(t).catch(()=>null)]));app.innerHTML=`<div class="panel"><h3>Sistema</h3><div class="row"><span>Supabase</span><b class="badge">Online</b></div><div class="row"><span>Administrador</span><b>${esc(sessionUser?.email)}</b></div></div><div class="panel"><h3>Banco de dados</h3>${stats.map(([t,n])=>`<div class="row"><span>${esc(t)}</span><b>${n===null?'Sem acesso':n+' registro(s)'}</b></div>`).join('')}</div>`}
const pages={overview:[overview,'Visão geral','Administração global da plataforma'],companies:[companies,'Empresas','Clientes cadastrados na plataforma'],auctions:[auctions,'Leilões','Visão global dos leilões'],users:[users,'Usuários','Acessos e perfis da plataforma'],finance:[finance,'Financeiro','Movimentação financeira global'],system:[system,'Sistema','Saúde e informações da plataforma']};
async function go(name){const p=pages[name]||pages.overview;title.textContent=p[1];subtitle.textContent=p[2];document.querySelectorAll('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));app.innerHTML='<div class="panel"><p>Carregando...</p></div>';try{await p[0]()}catch(e){fail(e)}}
document.querySelectorAll('#adminNav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
document.querySelector('#logoutButton').onclick=async()=>{await db.auth.signOut();location.href='login.html'};
document.querySelector('#clientPanel').onclick=()=>location.href='index.html';
document.querySelector('#menu').onclick=()=>document.body.classList.toggle('menu-open');
(async()=>{try{if(await assertAdmin())await go('overview')}catch(e){fail(e)}})();