const SUPABASE_URL='https://dsgnyfnddyxilakjwavu.supabase.co';
const SUPABASE_KEY='sb_publishable_4-pk8-WndWKwy_8plTVTAA_KXUNf-Lr';
const app=document.querySelector('#app'),statusEl=document.querySelector('#dbStatus'),title=document.querySelector('#title'),subtitle=document.querySelector('#subtitle');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>(+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),date=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const timeout=(p,ms=9000)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error('Tempo limite na consulta.')),ms))]);
let sessionUser=null;
function fail(e){console.error(e);statusEl.textContent='● Erro';statusEl.style.color='#ef4444';app.innerHTML=`<div class="panel"><h2>Não foi possível carregar a administração</h2><p>${esc(e?.message||e)}</p><button class="primary" onclick="location.reload()">Tentar novamente</button></div>`}
async function count(t){const{count,error}=await timeout(db.from(t).select('*',{count:'exact',head:true}));if(error)throw error;return count||0}
async function rows(t,s='*',o='created_at'){let q=db.from(t).select(s);if(o)q=q.order(o,{ascending:false});const{data,error}=await timeout(q);if(error)throw error;return data||[]}
async function assertAdmin(){const r=await timeout(db.auth.getSession());sessionUser=r?.data?.session?.user;if(!sessionUser){location.href='login.html';return false}document.querySelector('#userName').textContent=sessionUser.email||'Administrador';const{data,error}=await timeout(db.from('company_members').select('role').eq('user_id',sessionUser.id).eq('role','platform_admin').limit(1).maybeSingle());if(error)throw error;if(!data){app.innerHTML='<div class="panel"><h2>Acesso negado</h2></div>';return false}statusEl.textContent='● Banco online';statusEl.style.color='#22c55e';return true}
async function overview(){const [cs,as,us,bs,ps]=await Promise.all([rows('companies'),count('auctions'),count('company_members'),count('bids'),rows('payments').catch(()=>[])]);const active=cs.filter(x=>x.active&&x.subscription_status!=='blocked'&&x.subscription_status!=='suspended').length,suspended=cs.length-active,revenue=ps.reduce((s,p)=>s+(+p.amount||0),0);app.innerHTML=`<div class="cards"><div class="card"><small>Empresas ativas</small><h2>${active}</h2><span class="up">de ${cs.length} cadastradas</span></div><div class="card"><small>Empresas suspensas</small><h2>${suspended}</h2><span class="up">Bloqueadas ou inativas</span></div><div class="card"><small>Leilões</small><h2>${as}</h2><span class="up">Total registrado</span></div><div class="card"><small>Usuários vinculados</small><h2>${us}</h2><span class="up">Membros de empresas</span></div></div><div class="panels"><div class="panel"><h3>Administração global</h3><p>Gerencie clientes, planos, vencimentos e acessos da plataforma.</p><button class="primary" onclick="go('companies')">Gerenciar empresas</button></div><div class="panel"><h3>Financeiro</h3><div class="row"><span>Volume registrado</span><b>${money(revenue)}</b></div><div class="row"><span>Lances</span><b>${bs}</b></div><div class="row"><span>Status do banco</span><b class="badge">Conectado</b></div></div></div>`}
function companyForm(){return `<div class="panel"><div class="toolbar"><div><h3 style="margin:0">Nova empresa cliente</h3><p class="muted">Cadastre um novo cliente da plataforma.</p></div><button class="ghost" id="closeCompany">Fechar</button></div><form id="companyForm" class="grid2"><label>Nome da empresa<input name="name" required></label><label>CNPJ / CPF<input name="document"></label><label>Responsável<input name="responsible_name"></label><label>E-mail<input name="email" type="email"></label><label>Telefone<input name="phone"></label><label>Plano<select name="plan"><option value="teste">Teste</option><option value="basico" selected>Básico</option><option value="profissional">Profissional</option><option value="premium">Premium</option></select></label><label>Status<select name="subscription_status"><option value="trial">Teste</option><option value="active" selected>Ativa</option><option value="suspended">Suspensa</option><option value="blocked">Bloqueada</option></select></label><label>Vencimento<input name="subscription_expires_at" type="date"></label><div><button class="primary" type="submit">Cadastrar empresa</button></div></form></div>`}
async function companies(showForm=false){const data=await rows('companies');app.innerHTML=`${showForm?companyForm():''}<div class="panel"><div class="toolbar"><div><h3 style="margin:0">Empresas</h3><p class="muted">${data.length} empresa(s) cadastrada(s).</p></div><button class="primary" id="newCompany">+ Nova empresa</button></div><table><thead><tr><th>EMPRESA</th><th>RESPONSÁVEL</th><th>PLANO</th><th>VENCIMENTO</th><th>STATUS</th><th>AÇÕES</th></tr></thead><tbody>${data.map(x=>`<tr><td><b>${esc(x.name)}</b><br><small>${esc(x.email||x.document||'')}</small></td><td>${esc(x.responsible_name||'—')}</td><td><span class="badge">${esc(x.plan||'basico')}</span></td><td>${x.subscription_expires_at?new Date(x.subscription_expires_at).toLocaleDateString('pt-BR'):'—'}</td><td><span class="badge ${(!x.active||['suspended','blocked'].includes(x.subscription_status))?'warn':''}">${!x.active?'Inativa':esc(x.subscription_status||'active')}</span></td><td><button class="ghost mini toggleCompany" data-id="${x.id}" data-active="${x.active}">${x.active?'Suspender':'Ativar'}</button> <button class="ghost mini editCompany" data-id="${x.id}">Editar</button></td></tr>`).join('')||'<tr><td colspan="6">Nenhuma empresa.</td></tr>'}</tbody></table></div>`;
 document.querySelector('#newCompany').onclick=()=>companies(true); if(showForm){document.querySelector('#closeCompany').onclick=()=>companies();document.querySelector('#companyForm').onsubmit=createCompany}
 document.querySelectorAll('.toggleCompany').forEach(b=>b.onclick=()=>toggleCompany(b.dataset.id,b.dataset.active==='true'));document.querySelectorAll('.editCompany').forEach(b=>b.onclick=()=>editCompany(b.dataset.id,data));}
async function createCompany(e){e.preventDefault();const f=new FormData(e.currentTarget),name=f.get('name').trim(),slug=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString().slice(-5);const payload={name,slug,document:f.get('document')||null,responsible_name:f.get('responsible_name')||null,email:f.get('email')||null,phone:f.get('phone')||null,plan:f.get('plan'),subscription_status:f.get('subscription_status'),subscription_expires_at:f.get('subscription_expires_at')||null,active:true};const{error}=await db.from('companies').insert(payload);if(error)return alert('Erro: '+error.message);alert('Empresa cadastrada com sucesso.');companies()}
async function toggleCompany(id,isActive){if(!confirm(isActive?'Suspender esta empresa?':'Ativar esta empresa?'))return;const{error}=await db.from('companies').update({active:!isActive,subscription_status:isActive?'suspended':'active',updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert('Erro: '+error.message);companies()}
async function editCompany(id,data){const x=data.find(v=>v.id===id);if(!x)return;const plan=prompt('Plano: teste, basico, profissional ou premium',x.plan||'basico');if(plan===null)return;if(!['teste','basico','profissional','premium'].includes(plan))return alert('Plano inválido.');const status=prompt('Status: active, trial, suspended ou blocked',x.subscription_status||'active');if(status===null)return;if(!['active','trial','suspended','blocked'].includes(status))return alert('Status inválido.');const{error}=await db.from('companies').update({plan,subscription_status:status,active:!['suspended','blocked'].includes(status),updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert('Erro: '+error.message);companies()}
async function auctions(){const d=await rows('auctions');app.innerHTML=`<div class="panel"><h3>Leilões da plataforma</h3><table><thead><tr><th>TÍTULO</th><th>STATUS</th><th>EMPRESA</th><th>INÍCIO</th><th>FIM</th></tr></thead><tbody>${d.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td><span class="badge">${esc(x.status)}</span></td><td>${esc(x.company_id)}</td><td>${date(x.starts_at)}</td><td>${date(x.ends_at)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum leilão.</td></tr>'}</tbody></table></div>`}
async function users(){const d=await rows('company_members','company_id,user_id,role,created_at');app.innerHTML=`<div class="panel"><h3>Usuários e acessos</h3><table><thead><tr><th>USER ID</th><th>EMPRESA</th><th>PERFIL</th><th>CRIADO EM</th></tr></thead><tbody>${d.map(x=>`<tr><td>${esc(x.user_id)}</td><td>${esc(x.company_id)}</td><td><span class="badge">${esc(x.role)}</span></td><td>${date(x.created_at)}</td></tr>`).join('')}</tbody></table></div>`}
async function finance(){const d=await rows('payments').catch(()=>[]),total=d.reduce((s,p)=>s+(+p.amount||0),0);app.innerHTML=`<div class="cards"><div class="card"><small>Pagamentos</small><h2>${d.length}</h2></div><div class="card"><small>Volume</small><h2>${money(total)}</h2></div></div><div class="panel"><h3>Movimentações financeiras</h3>${d.length?`<table><thead><tr><th>ID</th><th>VALOR</th><th>STATUS</th><th>DATA</th></tr></thead><tbody>${d.map(x=>`<tr><td>${esc(x.id)}</td><td><b>${money(x.amount)}</b></td><td><span class="badge">${esc(x.status)}</span></td><td>${date(x.created_at)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Nenhum pagamento registrado.</p>'}</div>`}
async function system(){const ts=['companies','company_members','auctions','lots','bids','participants','payments'],stats=await Promise.all(ts.map(async t=>[t,await count(t).catch(()=>null)]));app.innerHTML=`<div class="panel"><h3>Sistema</h3><div class="row"><span>Supabase</span><b class="badge">Online</b></div><div class="row"><span>Administrador</span><b>${esc(sessionUser?.email)}</b></div></div><div class="panel"><h3>Banco de dados</h3>${stats.map(([t,n])=>`<div class="row"><span>${t}</span><b>${n===null?'Sem acesso':n+' registro(s)'}</b></div>`).join('')}</div>`}
const pages={overview:[overview,'Visão geral','Administração global da plataforma'],companies:[companies,'Empresas','Clientes, planos e assinaturas'],auctions:[auctions,'Leilões','Visão global dos leilões'],users:[users,'Usuários','Acessos e perfis da plataforma'],finance:[finance,'Financeiro','Movimentação financeira global'],system:[system,'Sistema','Saúde da plataforma']};
async function go(n){const p=pages[n]||pages.overview;title.textContent=p[1];subtitle.textContent=p[2];document.querySelectorAll('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===n));app.innerHTML='<div class="panel"><p>Carregando...</p></div>';try{await p[0]()}catch(e){fail(e)}}
document.querySelectorAll('#adminNav button').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelector('#logoutButton').onclick=async()=>{await db.auth.signOut();location.href='login.html'};document.querySelector('#clientPanel').onclick=()=>location.href='index.html';document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
(async()=>{try{if(await assertAdmin())await go('overview')}catch(e){fail(e)}})();