const crypto=require('crypto');
const {serviceFetch,serviceKey,authUser}=require('./mercadopago');

const templates=[
'Quer realizar leilões online com mais organização e controle?\n\nCom a JP Leilões você gerencia lotes, participantes, lances, arrematantes e pagamentos em um só lugar.\n\nComece com 4 dias grátis e conheça a plataforma.\n\n{site}\n\n#JPLeiloes #LeilaoOnline #GestaoDeLeiloes',
'Sua empresa pode ter uma operação de leilões online mais simples.\n\nA JP Leilões reúne cadastro de lotes, lances em tempo real, arrematantes e pagamentos em uma única plataforma.\n\nTeste grátis por 4 dias.\n\n{site}\n\n#Leiloes #Tecnologia #JPLeiloes',
'Está pensando em vender por leilão?\n\nA JP Leilões foi criada para empresas que querem administrar leilões online com autonomia, organização e visão de toda a operação.\n\nConheça a plataforma e comece seu teste gratuito.\n\n{site}\n\n#LeilaoOnline #Empresas #JPLeiloes',
'Leilão online não precisa ser complicado.\n\nNa JP Leilões você acompanha lances, lotes, participantes, arrematantes e pagamentos em tempo real.\n\nCrie sua conta e teste grátis por 4 dias.\n\n{site}\n\n#Gestao #LeiloesOnline #JPLeiloes',
'Uma plataforma pensada para quem vende por leilão.\n\n✓ Cadastro de lotes\n✓ Lances em tempo real\n✓ Controle de participantes\n✓ Arrematantes e pagamentos\n✓ Gestão da operação\n\nConheça a JP Leilões.\n\n{site}\n\n#JPLeiloes #Leilao #Negocios',
'Profissionalize a gestão dos seus leilões online.\n\nA JP Leilões centraliza sua operação e ajuda sua empresa a acompanhar cada etapa do leilão em um só painel.\n\nTeste a plataforma por 4 dias sem cobrança.\n\n{site}\n\n#LeiloesOnline #GestaoEmpresarial #JPLeiloes'
];

function tokenKey(){return crypto.createHash('sha256').update(`jp-marketing:${serviceKey()}`).digest()}
function encrypt(value){if(!value)return null;const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',tokenKey(),iv),encrypted=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]),tag=cipher.getAuthTag();return `v1.${iv.toString('base64url')}.${tag.toString('base64url')}.${encrypted.toString('base64url')}`}
function decrypt(value){if(!value)return null;const [v,iv64,tag64,data64]=String(value).split('.');if(v!=='v1')throw new Error('Token Meta inválido.');const decipher=crypto.createDecipheriv('aes-256-gcm',tokenKey(),Buffer.from(iv64,'base64url'));decipher.setAuthTag(Buffer.from(tag64,'base64url'));return Buffer.concat([decipher.update(Buffer.from(data64,'base64url')),decipher.final()]).toString('utf8')}

async function assertPlatformAdmin(req){const auth=String(req.headers.authorization||'');const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)throw new Error('Sessão administrativa necessária.');const user=await authUser(token);const rows=await serviceFetch(`/rest/v1/company_members?user_id=eq.${encodeURIComponent(user.id)}&role=eq.platform_admin&select=user_id&limit=1`);if(!Array.isArray(rows)||!rows[0]){const e=new Error('Acesso restrito ao administrador da plataforma.');e.status=403;throw e}return user}
async function getSettings(){const rows=await serviceFetch('/rest/v1/platform_marketing_settings?singleton=eq.true&select=*&limit=1');return Array.isArray(rows)?rows[0]||null:null}
async function patchSettings(data){const rows=await serviceFetch('/rest/v1/platform_marketing_settings?singleton=eq.true',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...data,updated_at:new Date().toISOString()})});return Array.isArray(rows)?rows[0]||null:null}
async function addLog(log){await serviceFetch('/rest/v1/platform_marketing_logs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(log)})}
function messageFor(settings){const i=Math.abs(Number(settings.template_index)||0)%templates.length;return templates[i].replaceAll('{site}',settings.site_url||'https://www.jpleiloes.com.br')}
async function graph(path,params){const version=process.env.META_GRAPH_VERSION||'v24.0';const r=await fetch(`https://graph.facebook.com/${version}/${path}`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});const data=await r.json().catch(()=>({}));if(!r.ok||data.error)throw new Error(data?.error?.message||'Falha na Meta Graph API.');return data}
async function publishFacebook(settings,token,message){if(!settings.facebook_page_id)throw new Error('Informe o ID da página do Facebook.');return graph(`${encodeURIComponent(settings.facebook_page_id)}/feed`,{message,access_token:token})}
async function publishInstagram(settings,token,message){if(!settings.instagram_account_id)throw new Error('Informe o ID da conta profissional do Instagram.');if(!settings.promo_image_url)throw new Error('Informe uma URL pública de imagem para o Instagram.');const media=await graph(`${encodeURIComponent(settings.instagram_account_id)}/media`,{image_url:settings.promo_image_url,caption:message,access_token:token});if(!media.id)throw new Error('A Meta não retornou o ID da mídia do Instagram.');return graph(`${encodeURIComponent(settings.instagram_account_id)}/media_publish`,{creation_id:media.id,access_token:token})}

async function publishConfigured({source='manual',ignoreDisabled=false}={}){const settings=await getSettings();if(!settings)throw new Error('Configuração de divulgação não encontrada.');if(!ignoreDisabled&&!settings.enabled)return {skipped:true,reason:'disabled'};if(!settings.access_token_enc)throw new Error('Conecte a Meta informando um token de acesso.');const token=decrypt(settings.access_token_enc),message=messageFor(settings),results=[];for(const network of ['facebook','instagram']){const active=network==='facebook'?settings.facebook_enabled:settings.instagram_enabled;if(!active)continue;try{const data=network==='facebook'?await publishFacebook(settings,token,message):await publishInstagram(settings,token,message);results.push({network,ok:true,id:data.id||data.post_id||null});await addLog({source,network,status:'sent',message,external_id:data.id||data.post_id||null})}catch(error){results.push({network,ok:false,error:error.message});await addLog({source,network,status:'failed',message,error:error.message})}}
await patchSettings({template_index:(Number(settings.template_index)||0)+1,last_published_at:new Date().toISOString()});return {skipped:false,message,results}}

module.exports={assertPlatformAdmin,getSettings,patchSettings,addLog,encrypt,publishConfigured,templates};