const crypto=require('crypto');
const {serviceFetch,serviceKey}=require('./mercadopago');

function key(){return crypto.createHash('sha256').update(`jp-meta:${serviceKey()}`).digest()}
function seal(value){if(!value)return null;const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([c.update(String(value),'utf8'),c.final()]);const tag=c.getAuthTag();return `v1.${iv.toString('base64url')}.${tag.toString('base64url')}.${data.toString('base64url')}`}
function open(value){if(!value)return'';const [v,iv,tag,data]=String(value).split('.');if(v!=='v1')throw new Error('Credencial Meta inválida.');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8')}
async function settings(){const r=await serviceFetch('/rest/v1/platform_marketing_settings?singleton=eq.true&select=*&limit=1');return Array.isArray(r)?r[0]||null:null}
async function patch(data){const r=await serviceFetch('/rest/v1/platform_marketing_settings?singleton=eq.true',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...data,updated_at:new Date().toISOString()})});return Array.isArray(r)?r[0]||null:null}
function redirectUri(){return process.env.META_REDIRECT_URI||'https://www.jpleiloes.com.br/api/marketing-meta-callback'}
function makeState(data){const body=Buffer.from(JSON.stringify(data)).toString('base64url');const sig=crypto.createHmac('sha256',key()).update(body).digest('base64url');return `${body}.${sig}`}
function readState(value){const [body,sig]=String(value||'').split('.');if(!body||!sig)throw new Error('Conexão Meta inválida.');const expected=crypto.createHmac('sha256',key()).update(body).digest('base64url');if(sig!==expected)throw new Error('Conexão Meta inválida.');const data=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));if(!data.exp||Date.now()>data.exp)throw new Error('Conexão Meta expirada.');return data}
async function app(){const s=await settings();const id=String(s?.meta_app_id||'').trim();const secret=s?.meta_app_secret_enc?open(s.meta_app_secret_enc):'';if(!id||!secret)throw new Error('Configure o App ID e o App Secret da Meta primeiro.');if(!/^\d{5,30}$/.test(id))throw new Error('App ID inválido. Informe o número do aplicativo da Meta, não seu e-mail.');return {id,secret}}
async function json(url){const r=await fetch(url);const data=await r.json().catch(()=>({}));if(!r.ok||data.error)throw new Error(data?.error?.message||'Falha ao conectar com a Meta.');return data}
async function exchangeCode(code){const a=await app();const qs=new URLSearchParams({client_id:a.id,client_secret:a.secret,redirect_uri:redirectUri(),code});const d=await json(`https://graph.facebook.com/v24.0/oauth/access_token?${qs}`);return d.access_token}
async function longLived(token){const a=await app();const qs=new URLSearchParams({grant_type:'fb_exchange_token',client_id:a.id,client_secret:a.secret,fb_exchange_token:token});const d=await json(`https://graph.facebook.com/v24.0/oauth/access_token?${qs}`);return d.access_token||token}
async function pages(token){const qs=new URLSearchParams({fields:'id,name,access_token,instagram_business_account{id,username}',limit:'100',access_token:token});const d=await json(`https://graph.facebook.com/v24.0/me/accounts?${qs}`);return Array.isArray(d.data)?d.data:[]}
async function storePages(list){return patch({meta_accounts_enc:seal(JSON.stringify(list||[])),meta_connected_at:new Date().toISOString()})}
async function publicPages(){const s=await settings();if(!s?.meta_accounts_enc)return[];let list=[];try{list=JSON.parse(open(s.meta_accounts_enc)||'[]')}catch{return[]}return list.map(p=>({id:String(p.id||''),name:String(p.name||''),instagramId:String(p.instagram_business_account?.id||''),instagramUsername:String(p.instagram_business_account?.username||'')})).filter(p=>p.id)}
async function selectPage(pageId){const s=await settings();if(!s?.meta_accounts_enc)throw new Error('Conecte sua conta Meta primeiro.');const list=JSON.parse(open(s.meta_accounts_enc)||'[]');const p=list.find(x=>String(x.id)===String(pageId));if(!p?.access_token)throw new Error('Token ativo da Página não encontrado.');const ig=p.instagram_business_account||{};return patch({facebook_page_id:String(p.id),facebook_page_name:String(p.name||''),instagram_account_id:ig.id?String(ig.id):null,instagram_username:ig.username?String(ig.username):null,access_token_enc:seal(String(p.access_token)),meta_connected_at:new Date().toISOString()})}
module.exports={seal,settings,patch,redirectUri,makeState,readState,app,exchangeCode,longLived,pages,storePages,publicPages,selectPage};